### ISSUE TITLE
Handle multi-word workflow names

### ISSUE THREAD

**Issue by boris-remo** [xembly/validate-workflow-status#2]
When I gave the workflow a workflow name that is multiple words it only tried to find a workflow with the first word of the passed value. Which causes an error.
```yml
      - name: Validate test outcome
        id: check
        continue-on-error: true
        uses: xembly/validate-workflow-status@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 'Pull Request Quality'
```

![image](https://user-images.githubusercontent.com/81965134/134904845-24372951-6897-4199-815e-c4acbfb1a4bd.png)
